favicon: https://raw.githubusercontent.com/TonyWu2333/pic/main/tony.jpg
banner: https://cdn.jsdelivr.net/npm/hassan-assets/navi/webstack_banner_cn.png

logo:
  expanded: https://s2.loli.net/2024/03/18/uXUstqaCPvSlp5e.png
  collapsed: https://s2.loli.net/2024/03/18/uXUstqaCPvSlp5e.png
  dark: https://s2.loli.net/2024/03/18/uXUstqaCPvSlp5e.png

flag:
  icon: flag-cn
  name: China

search: true

githubCorner: '<a href="https://github.com/tonywu2333" class="github-corner" aria-label="View source on GitHub"><svg width="66" height="66" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>'

menu:
  - name: 常用
    icon: fas fa-star
    config: 常用
  - name: 计算机技术
    icon: iconfont icon-code
    submenu:
      - name: 开源
        icon: far fa-window-maximize
        config: 开源
      - name: 前端
        icon: far fa-window-maximize
        config: 前端
      - name: 后端
        icon: fas fa-server
        config: 后端
      - name: 算法
        icon: fas fa-cubes
        config: 算法
      - name: 网安
        icon: fas fa-user-secret
        config: 网安
      - name: 人工智能
        icon: fas fa-user-astronaut
        config: 人工智能
  - name: 动漫
    icon: far fa-smile
    submenu:
      - name: 在线动漫观看
        config: 在线动漫观看
      - name: 动漫资源下载
        config: 动漫资源下载
  - name: 影视
    icon: fas fa-video
    config: 影视
  - name: 工具
    icon: fas fa-wrench
    config: 工具
  - name: 学习
    icon: iconfont icon-study
    config: 学习
  - name: 软件资源
    icon: fas fa-download
    config: 软件资源
  - name: 游戏
    icon: fas fa-gamepad
    submenu:
      - name: 游戏下载
        config: 游戏下载
      - name: minecraft
        config: minecraft
  - name: 音乐
    icon: fas fa-music
    config: 音乐
  - name: MMD
    icon: fas fa-child
    config: MMD


  # - name: 与我相关
  #   icon: far fa-star
  #   submenu:
  #     - name: 我站相关
  #       icon: iconfont icon-blog
  #       config: 我站相关
  #     - name: 社交平台
  #       icon: iconfont icon-social
  #       config: 社交平台
  # - name: 学习
  #   icon: iconfont icon-study
  #   submenu:
  #     - name: 大学常用
  #       icon: iconfont icon-book
  #       config: 大学常用
  #     - name: 英语雅思
  #       icon: iconfont icon-english
  #       config: 英语雅思
  # - name: 编程
  #   icon: iconfont icon-code
  #   config: 编程
  # - name: 前端
  #   icon: iconfont icon-cherry
  #   config: 前端
  # - name: 工具
  #   icon: fas fa-tools
  #   submenu:
  #     - name: 视图文素材
  #       icon: iconfont icon-video
  #       config: 视图文素材
  #     - name: 图片设计
  #       icon: iconfont icon-photo
  #       config: 图片设计
  #     - name: 其它
  #       icon: iconfont icon-about
  #       config: 其它
  # - name: 音乐
  #   icon: iconfont icon-music
  #   config: 音乐
  # - name: 友链
  #   icon: iconfont icon-blogroll
  #   config: 友链

about:
  url: /about_website/
  icon: far fa-heart
  name: 关于本站

aboutPage:
  website:
    head: 关于本站
    html: '<blockquote><p>没啥好说的</p></blockquote>'
  webmaster:
    head: 关于站长
    name: Tony Wu
    url: https://nav.tonywu.top
    img: https://s2.loli.net/2024/02/27/5hZq8I6JbdEzHQB.jpg
    description: 异世界的旅者
    html: ""

since: 2024

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: 本站总访问量$pv
  uv: 本站总访客数$uv

custom:
  head: # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <link rel="stylesheet" type="text/css" href="/css/custom.css">
    <link rel="stylesheet" type="text/css" href="//at.alicdn.com/t/font_2204525_jxth1d6fs6o.css">
    <link rel="stylesheet" href="//s1.hdslb.com/bfs/static/jinkela/long/font/regular.css" media="all" onload="this.media='all'" />
  body: # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <div class="bg"></div>
    <script src="/js/custom.js"></script>
    <script src="/js/lozad.min.js"></script>
js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
